export const headCells = [
    {
        id: 'numero_reporte',
        numeric: false,
        disablePadding: true,
        label: 'Número de Reporte',
        width: null,
        show: true,
        placeHolder: "#",
        type: "text", //text, number, date, select, none
    },
    {
        id: 'tag',
        numeric: false,
        disablePadding: false,
        label: 'TAG Equipo',
        width: null,
        show: true,
        placeHolder: "#",
        type: "text", 
        
    },
    {
        id: 'tag_detalle',
        numeric: false,
        disablePadding: false,
        label: 'Descripción Equipo',
        width: null,
        show: true,
        placeHolder: "#",
        type: "text", 
        
    },
    {
        id: 'items[0].descripcion_servicio',
        numeric: false,
        disablePadding: true,
        label: 'Descripción del Servicio',
        width: "400px",
        show: true,
        placeHolder: "Servicio",
        type: "text",
    },
    {
        id: 'items[0].cantidad',
        numeric: true,
        disablePadding: false,
        label: 'Cantidad',
        width: null,
        show: true,
        placeHolder: "#",
        type: "text", 
    },
    {
        id: 'items[0].tipo_actividad',
        numeric: false,
        disablePadding: true,
        label: 'Tipo de Actividad',
        show: true,
        placeHolder: "-",
        type: "text",
    },
    {
        id: 'items[0].clase',
        numeric: false,
        disablePadding: true,
        label: 'Clase de Actividad',
        show: true,
        placeHolder: "-",
        type: "text",
    },
    {
        id: 'inspector',
        numeric: false,
        disablePadding: true,
        label: 'Operador',
        width: "150px",
        show: true,
        placeHolder: "Operador",
        type: "text", 
    },
    {
        id: 'numero_orden',
        numeric: false,
        disablePadding: false,
        label: 'Número Orden',
        width: null,
        show: true,
        placeHolder: "#",
        type: "text", 
    },
    {
        id: 'cliente',
        numeric: false,
        disablePadding: true,
        label: 'Cliente',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text", 
    },
    {
        id: 'contrato',
        numeric: false,
        disablePadding: false,
        label: 'Contrato',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text", 
    },
    {
        id: 'unidad',
        numeric: false,
        disablePadding: true,
        label: 'Unidad',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text", 
    },
    {
        id: 'fecha_carga',
        numeric: false,
        disablePadding: false,
        label: 'Fecha Carga',
        width: "190px",
        show: true,
        placeHolder: "-",
        type: "date", 
    },
    {
        id: 'semana_carga',
        numeric: false,
        disablePadding: false,
        label: 'Semana Carga',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text", 
    },
    {
        id: 'fecha_inspeccion',
        numeric: false,
        disablePadding: false,
        label: 'Fecha Inspeccion',
        width: "190px",
        show: true,
        placeHolder: "-",
        type: "date", 
    },
    {
        id: 'semana_inspeccion',
        numeric: false,
        disablePadding: false,
        label: 'Semana Inspección',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text", 
    },
    {
        id: 'trabajo_terminado',
        numeric: false,
        disablePadding: false,
        label: 'Trabajo Terminado',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text", 
    },
    {
        id: 'informe_realizado',
        numeric: false,
        disablePadding: false,
        label: 'Informe Realizado',
        width: null,
        show: true,
        placeHolder: "-",
        type: "select",
    },
    {
        id: 'informe_fecha',
        numeric: false,
        disablePadding: false,
        label: 'Fecha Informe',
        width: null,
        show: true,
        placeHolder: "-",
        type: "date",
    },
    {
        id: 'remito_realizado',
        numeric: false,
        disablePadding: false,
        label: 'Remito Realizado',
        width: null,
        show: true,
        placeHolder: "-",
        type: "select",
    },
    {
        id: 'remito_numero',
        numeric: false,
        disablePadding: false,
        label: 'Número Remito',
        width: null,
        show: true,
        placeHolder: "-",
        type: "number",
    },
    {
        id: 'remito_fecha',
        numeric: false,
        disablePadding: false,
        label: 'Fecha Remito',
        width: null,
        show: true,
        placeHolder: "-",
        type: "date",
    },
    {
        id: 'certificado_realizado',
        numeric: false,
        disablePadding: false,
        label: 'Certificado Realizado',
        width: null,
        show: true,
        placeHolder: "-",
        type: "select",
    },
    {
        id: 'certificado_fecha',
        numeric: false,
        disablePadding: false,
        label: 'Certificado Fecha',
        width: null,
        show: true,
        placeHolder: "-",
        type: "date",
    },

    {
        id: 'items[0].codigo_servicio',
        numeric: false,
        disablePadding: false,
        label: 'Ítem Contrato',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text", 
    },
    {
        id: 'archivo',
        numeric: false,
        disablePadding: false,
        label: 'Archivo',
        width: null,
        show: true,
        placeHolder: "-",
        type: "none",
    },
    {
        id: 'observaciones',
        numeric: false,
        disablePadding: false,
        label: 'Observaciones',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text",
    },
    {
        id: 'modificado',
        numeric: false,
        disablePadding: false,
        label: 'Modificado',
        width: null,
        show: true,
        placeHolder: "-",
        type: "select",
    },
    {
        id: 'modificado_nombre',
        numeric: false,
        disablePadding: false,
        label: 'Modificado Nombre',
        width: null,
        show: true,
        placeHolder: "-",
        type: "text",
    },
    {
        id: 'modificado_fecha',
        numeric: false,
        disablePadding: false,
        label: 'Modificado Fecha',
        width: null,
        show: true,
        placeHolder: "-",
        type: "date",
    },

];